extends:
  - idm_small.yaml
  - data_calvin_gate_4090.yaml
  - adapter_vw2_official.yaml

experiment_name: vw2_hidden_mlp_action_head_calvin_4090

policy:
  variant: mlp
  hidden_dim: 512

idm:
  variant: bc
  use_future_codes: false
  use_past_actions: false
  code_source: gt
  mixed_code_training: false
  mixed_code_ratio_gt: 0.0
  mixed_code_ratio_pred: 0.0
  mixed_code_ratio_noisy: 0.0
  planner_checkpoint: ""

training:
  output_dir: ../../outputs/vw2_idm/vw2_hidden_mlp_action_head_calvin_4090
  max_epochs: 4

logging:
  wandb:
    enabled: false
